local plugin = require("config.plugin")
local pickers = require("features.pickers")

plugin.add({
  {
    "ibhagwan/fzf-lua",
    dependencies = {
      "nvim-tree/nvim-web-devicons",
    },
    opts = {
      { "fzf-native", "hide" },
      fzf_colors = true,
      files = {
        fd_opts = "--color=never --type f --hidden --follow --exclude .git",
      },
      grep = {
        rg_opts = [[--column --line-number --no-heading --color=always --smart-case --hidden --glob "!.git/*" -e]],
        search_paths = { "." },
      },
      oldfiles = {
        include_current_session = true,
      },
      winopts = {
        height = 0.85,
        width = 0.85,
        row = 0.5,
        col = 0.5,
        border = "single",
        preview = {
          default = "bat",
          border = "single",
          layout = "flex",
          vertical = "down:45%",
          horizontal = "right:55%",
        },
      },
    },
    keys = {
      { "<leader><space>", pickers.run("global"), desc = "Smart Find" },
      { "<leader>,", pickers.run("buffers"), desc = "Buffers" },
      { "<leader>/", pickers.run("live_grep"), desc = "Grep" },
      { "<leader>:", pickers.run("command_history"), desc = "Command History" },
      { "<leader>n", pickers.notifications, desc = "Notification History" },

      { "<leader>fb", pickers.run("buffers"), desc = "Buffers" },
      { "<leader>fc", pickers.config_files, desc = "Find Config File" },
      { "<leader>ff", pickers.run("files"), desc = "Find Files" },
      { "<leader>fg", pickers.run("git_files"), desc = "Find Git Files" },
      { "<leader>fp", pickers.projects, desc = "Projects" },
      { "<leader>fr", pickers.run("oldfiles"), desc = "Recent" },

      { "<leader>gb", pickers.run("git_branches"), desc = "Git Branches" },
      { "<leader>gl", pickers.run("git_commits"), desc = "Git Log" },
      { "<leader>gL", pickers.run("git_blame"), desc = "Git Log Line" },
      { "<leader>gs", pickers.run("git_status"), desc = "Git Status" },
      { "<leader>gS", pickers.run("git_stash"), desc = "Git Stash" },
      { "<leader>gd", pickers.run("git_hunks"), desc = "Git Diff Hunks" },
      { "<leader>gf", pickers.run("git_bcommits"), desc = "Git Log File" },
      { "<leader>gi", pickers.gh("issue", "open"), desc = "GitHub Issues (open)" },
      { "<leader>gI", pickers.gh("issue", "all"), desc = "GitHub Issues (all)" },
      { "<leader>gp", pickers.gh("pr", "open"), desc = "GitHub Pull Requests (open)" },
      { "<leader>gP", pickers.gh("pr", "all"), desc = "GitHub Pull Requests (all)" },

      { "<leader>sb", pickers.run("blines"), desc = "Buffer Lines" },
      { "<leader>sB", pickers.run("lines"), desc = "Open Buffer Lines" },
      { "<leader>sg", pickers.run("live_grep"), desc = "Grep" },
      { "<leader>sw", pickers.grep_word, desc = "Visual selection or word", mode = { "n", "x" } },
      { '<leader>s"', pickers.run("registers"), desc = "Registers" },
      { "<leader>s/", pickers.run("search_history"), desc = "Search History" },
      { "<leader>sa", pickers.run("autocmds"), desc = "Autocmds" },
      { "<leader>sc", pickers.run("command_history"), desc = "Command History" },
      { "<leader>sC", pickers.run("commands"), desc = "Commands" },
      { "<leader>sd", pickers.run("diagnostics_workspace"), desc = "Diagnostics" },
      { "<leader>sD", pickers.run("diagnostics_document"), desc = "Buffer Diagnostics" },
      { "<leader>sh", pickers.run("helptags"), desc = "Help Pages" },
      { "<leader>sH", pickers.run("highlights"), desc = "Highlights" },
      { "<leader>si", pickers.icons, desc = "Icons" },
      { "<leader>sj", pickers.run("jumps"), desc = "Jumps" },
      { "<leader>sk", pickers.run("keymaps"), desc = "Keymaps" },
      { "<leader>sl", pickers.run("loclist"), desc = "Location List" },
      { "<leader>sm", pickers.run("marks"), desc = "Marks" },
      { "<leader>sM", pickers.run("manpages"), desc = "Man Pages" },
      { "<leader>sp", pickers.plugin_specs, desc = "Search for Plugin Spec" },
      { "<leader>sq", pickers.run("quickfix"), desc = "Quickfix List" },
      { "<leader>sR", pickers.run("resume"), desc = "Resume" },
      { "<leader>su", pickers.run("undotree"), desc = "Undo History" },
      { "<leader>uC", pickers.run("colorschemes"), desc = "Colorschemes" },

      { "gd", pickers.run("lsp_definitions"), desc = "Goto Definition" },
      { "gD", pickers.run("lsp_declarations"), desc = "Goto Declaration" },
      { "gr", pickers.run("lsp_references"), nowait = true, desc = "References" },
      { "gI", pickers.run("lsp_implementations"), desc = "Goto Implementation" },
      { "gy", pickers.run("lsp_typedefs"), desc = "Goto Type Definition" },
      { "gai", pickers.run("lsp_incoming_calls"), desc = "Calls Incoming" },
      { "gao", pickers.run("lsp_outgoing_calls"), desc = "Calls Outgoing" },
      { "<leader>ss", pickers.run("lsp_document_symbols"), desc = "LSP Symbols" },
      { "<leader>sS", pickers.run("lsp_workspace_symbols"), desc = "LSP Workspace Symbols" },
      { "<leader>st", pickers.todo(), desc = "Todo" },
      { "<leader>sT", pickers.todo({ "TODO", "FIX", "FIXME" }), desc = "Todo/Fix/Fixme" },
    },
  },
})
